### ISSUE TITLE
Uncaught Exceptions in `internal/HelperMethod.js`

### ISSUE THREAD

**Issue by jornverhoeven** [Cryptolens/cryptolens-nodejs#21] opened 2022-08-08 13:53 UTC
For some (yet undetermined) reason the response of the `Key.Activate` returns a `502` - HTML page, instead of a JSON object. 
This causes the `cryptolens/internal/HelperMethods.js:47:47` to throw an error as it tries to parse a non-JSON string.

Because this `JSON.parse` throws an error, inside of the catch-block, it becomes uncaught. Therefore breaking the `reject` from the promises and causing a lot of strange side effects.

A workaround would be to change the catch of the `HelperMethods:CallAPI` to 

```javascript
if (error.name === "HTTPError") {
    reject(safeParseError(error));
} else {
    reject(error);
}
```

Where `safeParseError` would be something like this:
```javascript
function safeParseError(error) {
    try {
        return new Error(JSON.parse(error.response.body).message)
    } catch (e) {
        return new Error("Could not perform api call")
    }
}
```

This is by no means a production ready fix, but its something to get started on.

**Some additional Error logs:**
The URL for the api call `https://api.cryptolens.io//api/key/Activate`

The webpage content:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>502 - Web server received an invalid response while acting as a gateway or proxy server.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>
  <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.</h3>
 </fieldset></div>
</div>
</body>
</html>
```

**Comment by artemlos** [comment] 2022-08-08 14:58
@jornverhoeven Thanks for reporting this issue and for the feedback.

I have a question regarding the parameters to Key.Activate. Has the `LicenseServerUrl` (in [Activate](https://github.com/Cryptolens/cryptolens-nodejs/blob/master/methods/Key.js#L6)) been changed to a different one or is the default being used?

The problem is that the API is called with an extra `/`, i.e. `https://api.cryptolens.io//api/key/Activate` will fail but `https://api.cryptolens.io/api/key/Activate` will succeed.

The only reason I can think of that could have caused this is that Key.Activate was called with `LicenseServerUrl` set to `https://api.cryptolens.io/` and not the default `https://api.cryptolens.io`.

**Comment by artemlos** [comment] 2022-08-09 12:06
@jornverhoeven A new version was released that incorporates your suggested changes. The error message was updated to advise users to double check the presence of `/` in the `LicenseServerUrl` as this seems to be the only cause of the response being returned in non-JSON format: https://github.com/Cryptolens/cryptolens-nodejs/commit/f757536469f855c99e308380e8c1c7b340ceba6e

Thanks again for your feedback and the code!

I will close the issue since the cause of the initial error was identified and the suggested code that catches the error was incorporated into the package.

**Closed by artemlos** 2022-08-09 12:06 UTC
