### ISSUE TITLE
Dependencies out of date

### ISSUE THREAD

**Issue by roelvanegmond** [Cryptolens/cryptolens-nodejs#10] opened 2022-04-15 11:25 UTC
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, 
which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

**Comment by AlejandroSotoCastro** [comment] 2022-04-28 08:07
I believe this is no longer an issue.

**Comment by artemlos** [comment] 2022-04-28 08:27
@AlejandroSotoCastro I think so too, since there is no longer a `dependency` on the request package, which seems to have been the root cause.

I will close it for now.

**Closed by artemlos** 2022-04-28 08:27 UTC
